### ISSUE TITLE
Installation problem 

### ISSUE THREAD

**Issue by Suspectxyzz** [meanwhiletothestars/CS2_DMA_Radar#47]
I know it has nothing to do with the radar, but I said maybe you know that I just reinstalled windows and I get this error
install python-3.12.3-amd64
pip install -r requirements.txt

`pygame 2.5.2 (SDL 2.28.3, Python 3.12.3)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "C:\Users\Server\Desktop\CS2_DMA\app.py", line 5, in <module> import pygame_gui
  File "C:\Users\Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\pygame_gui\__init__.py", line 7, in <module> from pygame_gui.ui_manager import UIManager

  File "C:\Users\Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\pygame_gui\ui_manager.py", line 8, in <module> from pygame_gui.core.interfaces import IUIManagerInterface

  File "C:\Users\Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\pygame_gui\core\__init__.py", line 1, in <module>  from pygame_gui.core.ui_appearance_theme import UIAppearanceTheme

  File "C:\Users\Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\pygame_gui\core\ui_appearance_theme.py", lin11, in <module> from pygame_gui.core.interfaces.gui_font_interface import IGUIFontInterface

  File "C:\Users\Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\pygame_gui\core\interfaces\__init__.py", line 2, in <module>  from pygame_gui.core.interfaces.font_dictionary_interface import IUIFontDictionaryInterface

  File "C:\Users\Server\AppData\Local\Programs\Python\Python312\Lib\sitepackages\pygame_gui\core\interfaces\font_dictionary_interface.py", line 2, in <module>
    from pygame import DIRECTION_LTR
ImportError: cannot import name 'DIRECTION_LTR' from 'pygame' (C:\Users\Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\pygame\__init__.py)
`

**Comment by therewillwhile** [comment]
for the first u can try install python 3.11

**Comment by Suspectxyzz** [comment]
> for the first u can try install python 3.11

same for 3.11 / 3.12/3.13

![image](https://github.com/meanwhiletothestars/CS2_DMA_Radar/assets/45514952/00ca9472-701c-48ff-bcab-abeb049c8642)

**Comment by therewillwhile** [comment]
there is no errors on provided screenshot

**Comment by Suspectxyzz** [comment]
> there is no errors on provided screenshot
same for 3.11 / 3.12/3.13 error
![image](https://github.com/meanwhiletothestars/CS2_DMA_Radar/assets/45514952/9ba02458-f4b1-4da1-bf2f-88f5d852421a)

**Comment by therewillwhile** [comment]
try earlier version of pygame and pygame_gui

**Comment by Suspectxyzz** [comment]
it doesn't work but I will reinstall windows :0
