### ISSUE TITLE
What does this error mean?

### ISSUE THREAD

**Issue by shiwu924** [meanwhiletothestars/CS2_DMA_Radar#60]
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\CS2_DMA_Radar-DMA\CS2_DMA_Radar-DMA\app.py", line 260, in <module>
    mapname = readmapfrommem()
              ^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Downloads\CS2_DMA_Radar-DMA\CS2_DMA_Radar-DMA\app.py", line 170, in readmapfrommem
    mapname = read_string(dwGlobalVarsvaradress)
              ^^^^^^^^^^^
NameError: name 'read_string' is not defined

As above, how can I solve it?

**Comment by therewillwhile** [comment]
download LATEST
